name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        host: http:198.244.232.17
        username: ubuntu
        password: b8YtGqq8qrYS
      with:
        source: "."
        target: "/your/website/directory"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: http:198.244.232.17
        username: ubuntu
        password: b8YtGqq8qrYS
        script: ls
